title: Themestrap
version: 0.3.0
AUTHOR_NAME: Your Name
REPO_URL:
PACKAGE_NAME:
  
# ---------------
# gh-pages config
permalink: /examples/:title 

# this is the closest to pandoc ^^
markdown: kramdown

# always on @github
pygments: true

# ignore some stuff
exclude:
  - node_modules
  - bower_components